language: cpp
dist: trusty

compiler:
   - gcc
   - clang

addons:
  apt:
    packages:
      - cmake
      - doxygen
  sonarcloud:
    organization: "stefanobelli-github"
    token:
      secure: "XUvVU6Lht45a6sLbCCU8tPBWNeYKsMohNv6mocpS0W9Dwa6fKKKUUMbeoFcjsVng56y+okj4WJcajWftQzhwv3njRZYyladksIQEEbbH8Z6SCREelWpKxsnguUBI9CCj6QL1QYjI9mkosqVV9kXqFMhHnq9D7kUYvxUHxJh7qI4GtPdsD2eUx9EPzmozyq+Qw5D4K6EUG0PGHrkkgrZeDZl0lojWbViIVPBYkQx3B0WsOd7CPKyw9KbIEnyZ9wEUFUAbLgWjQXtaZGydZ3195ZD5PEQIws/kiZfz9fVnudmtadNGvmlueL96kH1xmrPEneTskZwRIPqQ0iD8R8gPgTcWgkmhB35uSboBzxgQN3V/kjzEngMuczap0YpIs62PBOTyWwdxwBA7AVx0nZUc56EQoZoqkA8Wb4rL82lK6rzZYGVVPClv0FZN4jxyDqQcLYC0j7p7aQwNsW07yMI5PVHzSyBRhopqCXubrTObuSX8Q9eZooNbu8OgR6+STLrQJX8ugTKZSMhlrknpu1iLfDGjrXBtldhJrUFDhhG5dnmXL1rGK+MnDR/hfDy01axOJ/wAQVY7sPD/5fxiI9ocV35GYxV4l80E+6IaWNTZc9vN6sTvt6HF9H7hLXv/jCx9QfRuuzkTF9YXP3p1X4bbyyAbbZOfOVSuC8fzfiJSzik="


###
script:
   - cmake . -DCMAKE_BUILD_TYPE="Release" -DCMAKE_CXX_FLAGS="-Wall -Wextra -W -finline-functions -funroll-loops -O2 -s"
   - build-wrapper-linux-x86-64 --out-dir build_wrapper make -j3
   - cmake . -DCMAKE_BUILD_TYPE="Release" -DCMAKE_CXX_FLAGS="-Wall -Wextra -W -finline-functions -funroll-loops -O2 -s" -DLIBRARY="shared"
   - make -j3
   - sonar-scanner

###
before_deploy:
   - bash ./scripts/deploy_all.sh

deploy:
   - provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN
   on:
     branch: stable
   - provider: releases
   skip_cleanup: true
   file_glob: true
   file: "scripts/*.zip"
   user: "StefanoBelli"
   password:
		secure: "gPINtf7AZtHwbjEoBsX7utTFfKBuPOBqD6NyoiRGX9EmIL0kjTQjpGSDf/DOj37ukH5MKb+b0E2CED0/1mfb3zTBTNoNUgpVR7x7RXM9w6ml7W7A2pAGvV78xJbFsIP2C2PuYUCE79c6Ab7RY6ddRqQ3sLWcAWuuzBdpJV12LubAlE2sZGqMihrXTRiWz1MEX8ZQcIddrvwSzuBwLkdwldpYVsu9SORpcVdR9ZaiMF0zuKRSvARqfHY9FO+R7aoTMitvC9bqt9z6LKnJU73XvLG1PJKstcJypGS4uun9kRpTbvaaFIKfrTquW13yMwZJm0A8PhAoM8zPm/IiZg4Nn1qPg/bsGQjL1dMYbpuL3Ck1jCbktsZSHxlOhor0f7gG+Fu5gwytUJGXZLAEFAXw4R791+OxbMbKNn01EwwX+GmFZOuOlGhv9cPUx6oCli58F0dd+WSygX/vXFNXOcisCTlB3fVEnZ3kvIqvAathh0ur+KY1ClKQ1g5AZeSNez6c1mIbi36/GlsiuW3jhgxDsg7ukLicntVofgk/q0lqOIkeH8K5urTchtJh20emuNY6jeTIrjbDgifKaegPLfyxyrgmRb0g+v6cmf97fCpUN5hyi4SKPncK+QhlZnoDhJIOAr1vvFQPziR5qMx5Mi43Rvp5OVVslCtIZSy2xWFKecM="
	on:
		branch: stable
		tags: true
