language: cpp
dist: trusty

compiler:
   - gcc
   - clang

matrix:
    include:
        - compiler: clang
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                      - llvm-toolchain-trusty-5.0
                  packages:
                      - clang-5.0
              env:
                  CC=clang-5.0

addons:
  apt:
    packages:
      - cmake
      - doxygen

###
script:
   - cmake . -DCMAKE_BUILD_TYPE="Release" -DCMAKE_CXX_FLAGS="-Wall -Wextra -W -finline-functions -funroll-loops -O2" -DMAKE_TESTS="yes"
   - make -j3
   - env CTEST_OUTPUT_ON_FAILURE=1 make test
   - ./scripts/coverage.sh . coverage-results

###
before_deploy:
   - bash ./scripts/deploy_pages.sh

deploy:
   provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN
   on:
     tags: true
