language: cpp
dist: trusty

compiler:
   - gcc
   - clang

addons:
  apt:
    packages:
      - cmake
      - doxygen
  sonarcloud:
    organization: "stefanobelli-github"
    token:
      secure: "XUvVU6Lht45a6sLbCCU8tPBWNeYKsMohNv6mocpS0W9Dwa6fKKKUUMbeoFcjsVng56y+okj4WJcajWftQzhwv3njRZYyladksIQEEbbH8Z6SCREelWpKxsnguUBI9CCj6QL1QYjI9mkosqVV9kXqFMhHnq9D7kUYvxUHxJh7qI4GtPdsD2eUx9EPzmozyq+Qw5D4K6EUG0PGHrkkgrZeDZl0lojWbViIVPBYkQx3B0WsOd7CPKyw9KbIEnyZ9wEUFUAbLgWjQXtaZGydZ3195ZD5PEQIws/kiZfz9fVnudmtadNGvmlueL96kH1xmrPEneTskZwRIPqQ0iD8R8gPgTcWgkmhB35uSboBzxgQN3V/kjzEngMuczap0YpIs62PBOTyWwdxwBA7AVx0nZUc56EQoZoqkA8Wb4rL82lK6rzZYGVVPClv0FZN4jxyDqQcLYC0j7p7aQwNsW07yMI5PVHzSyBRhopqCXubrTObuSX8Q9eZooNbu8OgR6+STLrQJX8ugTKZSMhlrknpu1iLfDGjrXBtldhJrUFDhhG5dnmXL1rGK+MnDR/hfDy01axOJ/wAQVY7sPD/5fxiI9ocV35GYxV4l80E+6IaWNTZc9vN6sTvt6HF9H7hLXv/jCx9QfRuuzkTF9YXP3p1X4bbyyAbbZOfOVSuC8fzfiJSzik="


###
script:
   - cmake . -DCMAKE_BUILD_TYPE="Release" -DCMAKE_CXX_FLAGS="-Wall -Wextra -W -finline-functions -funroll-loops -O2" -DMAKE_TESTS="yes"
   - build-wrapper-linux-x86-64 --out-dir build_wrapper make -j3
   - env CTEST_OUTPUT_ON_FAILURE=1 make test
   - ./scripts/coverage.sh . coverage-results
   - sonar-scanner

###
before_deploy:
   - bash ./scripts/deploy_pages.sh

deploy:
   provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN
   on:
     tags: true
