language: cpp
dist: trusty

compiler:
   - gcc

addons:
  apt:
    packages:
      - cmake
      - doxygen

before_install:
    - pip install --user cpp-coveralls

###
script:
   - cmake . -DCMAKE_BUILD_TYPE="Release" -DCMAKE_CXX_FLAGS="-Wall -Wextra -W -finline-functions -funroll-loops -O2" -DMAKE_TESTS="yes"
   - make -j3
   - env CTEST_OUTPUT_ON_FAILURE=1 make test

after_success:
   - ./scripts/coverage.sh . coverage-results
   - cd coverage-results
   - coveralls

###
before_deploy:
   - bash ./scripts/deploy_pages.sh

deploy:
   provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN
   on:
     tags: true
