language: cpp
dist: trusty

compiler:
   - gcc

addons:
  apt:
    packages:
      - cmake
      - doxygen
      - lcov

before_script:
  - gem install coveralls-lcov 

###
script:
   - cmake . -DCMAKE_BUILD_TYPE="Release" -DCMAKE_CXX_FLAGS="-Wall -Wextra -W -O0 --coverage" -DMAKE_TESTS="yes"
   - make -j3
   - env CTEST_OUTPUT_ON_FAILURE=1 make test

after_success:
   - ./scripts/coverage.sh . coverage-results
   - cd coverage-results
   - lcov --directory . -c -o coverage.info
   - lcov --remove coverage.info '/usr/include/*' '/home/travis/build/erebos-project/erebos-api/test/*' -o coverage.info
   - lcov --list coverage.info
   - coveralls-lcov --repo-token $COVERALLS_REPO_TOKEN coverage.info
   - cd ..

###
before_deploy:
   - bash ./scripts/deploy_pages.sh

deploy:
   provider: pages
   skip_cleanup: true
   github_token: $GITHUB_TOKEN
