language: cpp

dist: trusty

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - cmake

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE="Release"
  - make -j3
  - cd ..
