language: cpp

compiler: 
  - gcc
  - clang
  
addons:
  apt:
    packages:
      - cmake

script:
  - mkdir build-gcc
  - cd build-gcc
  - cmake .. -DCMAKE_CXX_COMPILER="g++"
  - make -j3
  - cd ..
  - mkdir build-clang
  - cd build-clang
  - cmake .. -DCMAKE_CXX_COMPILER="clang++"
  - make -j3
