version: "{build}-{branch}"

image: Visual Studio 2015

platform:
  - x86

configuration:
  - Release
 
matrix: fast_finish: true

init:
  - cmake --version

before_build:
  - md build
  - cd build
  - cmake .. -DMAKE_TESTS="yes" -DCMAKE_CXX_FLAGS="/O2 /EHsc /W2" -DCMAKE_BUILD_TYPE="Release" -G "Visual Studio 14 2015"
