version: "{build}-{branch}"

platform:
  - Win32

init:
  - cmake --version

before_build:
  - md build
  - cd build
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - cmake .. -G "NMake Makefiles" -DMAKE_TESTS="yes" -DCMAKE_CXX_FLAGS="/O2 /EHsc /W2" -DCMAKE_BUILD_TYPE="Release"
