version: "{build}-{branch}"

platform:
  - Win32

init:
  - cmake --version

before_build:
  - md build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE="Release" -G "Visual Studio 14 2015" -DCMAKE_CXX_FLAGS="/O2 /W2 /EHsc" -DMAKE_TESTS="yes"

after_build:
  - ctest
